# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1420490540);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1420490660);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1420490180);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1420490420);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1420490300);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 225280);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141203173539");
user_pref("browser.slowStartup.averageTime", 5042);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "http://127.0.0.1/");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"31.3.0\",\"DEVTOOLS_NETMONITOR_OPENED_PER_USER_FLAG\":\"31.3.0\"}");
user_pref("devtools.toolbox.selectedTool", "netmonitor");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.3.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1420412852000,\"rdfTime\":1417629758000}}}]");
user_pref("extensions.lastAppVersion", "31.3.0");
user_pref("extensions.lastPlatformVersion", "31.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141203173539");
user_pref("gecko.mstone", "31.3.0");
user_pref("idle.lastDailyNotification", 1420490535);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1420490535);
user_pref("places.history.expiration.transient_current_max_pages", 12450);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1420490535);
user_pref("toolkit.startup.last_success", 1420491232);
user_pref("toolkit.telemetry.previousBuildID", "20141203173539");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
